### PR TITLE
[Coral-769] Fix `getPartitions` to work with compression

### LINKED ISSUE #769: Fix DataSkewRuntimePass to play well with compression
DataSkewRuntimePass balances data distribution based on partition size. Compression reduces partition size, and I've noticed DataSkewRuntimePass conflicts with CompressionPass. (Program executes well, but it gives wrong result.) We need a fix on DataSkewRuntimePass.

### PR DESCRIPTION
**Pull request by skystar-p**
* Fix `FileBlock#getPartitions` to skip unread bytes.
* `LimitedInputStream` implementation for limiting overreading `FileInputStream`.
* Add compression to `BlockStoreTest`.
* Add `CompressionPass` in `PrimitiveCompositePass`.

This PR fixes an issue about `DataSkewRuntimePass` not working properly with `CompressionPass`.

Resolves #769

### CODE REVIEW

File: runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java [hunk 1]
```diff
@@ -120,9 +120,12 @@ private void writeSerializedPartitions(final Iterable<SerializedPartition<K>> se
         final K key = partitionMetadata.getKey();
         if (keyRange.includes(key)) {
           // The key value of this partition is in the range.
+          final byte[] serializedData = new byte[partitionMetadata.getPartitionSize()];
+          fileStream.read(serializedData);
+          final ByteArrayInputStream byteInputStream = new ByteArrayInputStream(serializedData);
```
Comment (sanha) [inline runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: These `reading byte array - making it another stream - reading the stream again` process can lead memory & computation overhead. How about adding a new interface in `DataUtil#deserializePartition` which consumes byte array instead of stream?

Comment (skystar-p) [reply runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: @sanha `DataUtil#deserializePartition` uses `InputStreamIterator` to decode data, which takes `InputStream` as a parameter. Even if we do not use `InputStreamIterator`, we must call `buildInputStream` to get original data from the source, which means we eventually have to build a stream which contains serialized data. I want some advice for an idea to make `deserializePartition` method to not use stream but only byte array.

Comment (skystar-p) [reply runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: @sanha Now working with all kind of compression we support. Also not using extra stream and memory.

File: runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java [hunk 2]
```diff
@@ -120,10 +121,19 @@ private void writeSerializedPartitions(final Iterable<SerializedPartition<K>> se
...
               DataUtil.deserializePartition(
                   partitionMetadata.getElementsTotal(), serializer, key, fileStream);
           deserializedPartitions.add(deserializePartition);
+          // rearrange file pointer
+          final long toSkip = partitionMetadata.getPartitionSize() - availableBefore + fileStream.available();
+          if (toSkip > 0) {
+            skipBytes(fileStream, toSkip);
+          } else if (toSkip < 0) {
+            final FileChannel fc = fileStream.getChannel();
+            fc.position(fc.position() + toSkip);
```
Comment (sanha) [inline runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: We should avoid to use `FileChannel#position` method. We've experienced it's malfunction for a while.

Comment (skystar-p) [reply runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: @sanha Fixed. Thank you!

File: runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java [hunk 3]
```diff
@@ -120,10 +120,20 @@ private void writeSerializedPartitions(final Iterable<SerializedPartition<K>> se
         final K key = partitionMetadata.getKey();
         if (keyRange.includes(key)) {
           // The key value of this partition is in the range.
+          final long availableBefore = fileStream.available();
+          final LimitedInputStream limitedInputStream =
```
Comment (sanha) [inline runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: Now it seems reasonable to me. I have one more (and maybe last) suggestion.
How about include this stream in the `StreamChainer`?

Comment (sanha) [reply runtime/executor/src/main/java/edu/snu/coral/runtime/executor/data/block/FileBlock.java]: We decided to not put it in `StreamChainer` because the size of the partition have to be known before it's construction.
